"""
LangGraph 工作流可视化工具模块。

该模块提供了用于可视化和导出 LangGraph 工作流的实用工具函数。
支持 Mermaid 格式、ASCII 艺术和 JSON 格式的工作流可视化。
"""

import json
from typing import Optional, Literal
from pathlib import Path
from langgraph.graph.state import CompiledStateGraph

# 尝试导入 MermaidDrawArgs，如果不存在则使用空字典
try:
    from langgraph.graph import MermaidDrawArgs
except ImportError:
    # 旧版本或不同版本的 LangGraph 可能没有这个类
    MermaidDrawArgs = None


def get_graph_mermaid(
    workflow: CompiledStateGraph, title: str = "Workflow Graph", xray: bool = False
) -> str:
    """获取工作流的 Mermaid 格式图表。

    该函数提取编译后的工作流并生成 Mermaid 格式的图表代码，
    可用于文档、Markdown 文件或支持 Mermaid 的平台。

    Args:
        workflow: 编译后的工作流 (CompiledStateGraph)
        title: 图表标题，用于添加注释头部
        xray: 是否启用 X 射线模式（显示更多内部细节）

    Returns:
        Mermaid 格式的图表代码字符串

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)
        >>> mermaid_code = get_graph_mermaid(workflow, "查询工作流")
        >>> print(mermaid_code)
    """
    try:
        # 获取图对象
        graph = workflow.get_graph()

        # 生成 Mermaid 代码
        # 尝试使用 draw_mermaid 方法
        if hasattr(graph, "draw_mermaid"):
            if MermaidDrawArgs is not None:
                # 新版本 LangGraph
                mermaid_code = graph.draw_mermaid(MermaidDrawArgs(curve_style="linear"))
            else:
                # 旧版本或不支持参数的版本
                mermaid_code = graph.draw_mermaid()
        elif hasattr(graph, "print_mermaid"):
            # 使用 print_mermaid 作为备选
            mermaid_code = graph.print_mermaid()
        else:
            # 最后的备选方案：使用 draw_mermaid_png 的文本版本
            import io
            from contextlib import redirect_stdout

            f = io.StringIO()
            try:
                with redirect_stdout(f):
                    # 尝试直接打印
                    print(graph)
                mermaid_code = f.getvalue()
            except Exception:
                mermaid_code = "%% Unable to generate Mermaid diagram from this graph"

        # 添加标题注释
        if title and isinstance(mermaid_code, str):
            header = (
                f"%% {title}\n%% Generated by Medical-Graph-RAG Visualization Module\n"
            )
            mermaid_code = header + mermaid_code

        return mermaid_code

    except Exception as e:
        return f"%% Error generating Mermaid diagram: {str(e)}"


def save_graph_mermaid(
    workflow: CompiledStateGraph, output_path: str, title: str = "Workflow Graph"
) -> None:
    """保存工作流图为 Mermaid 文件。

    将工作流的 Mermaid 表示保存到指定路径的文件中。
    文件扩展名通常为 .mmd 或 .mermaid。

    Args:
        workflow: 编译后的工作流
        output_path: 输出文件的完整路径
        title: 图表标题

    Raises:
        IOError: 如果文件写入失败
        ValueError: 如果 workflow 为 None

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)
        >>> save_graph_mermaid(workflow, "query_workflow.mmd", "查询工作流")
    """
    if workflow is None:
        raise ValueError("Workflow cannot be None")

    # 生成 Mermaid 代码
    mermaid_code = get_graph_mermaid(workflow, title)

    # 确保输出目录存在
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # 写入文件
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(mermaid_code)


def print_graph(
    workflow: CompiledStateGraph, title: str = "Workflow Graph", xray: bool = False
) -> None:
    """打印工作流结构到控制台。

    在终端中以美观的格式打印工作流的 Mermaid 图表。
    适合快速查看和调试工作流结构。

    Args:
        workflow: 编译后的工作流
        title: 图表标题
        xray: 是否启用 X 射线模式

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)
        >>> print_graph(workflow, "查询工作流")
    """
    # 生成 Mermaid 代码
    mermaid_code = get_graph_mermaid(workflow, title, xray)

    # 打印分隔线和标题
    separator = "=" * 80
    print(f"\n{separator}")
    print(f"{title:^80}")
    print(f"{separator}\n")

    # 打印 Mermaid 代码
    print(mermaid_code)

    # 打印使用提示
    print(f"\n{separator}")
    print("💡 提示: 复制上述 Mermaid 代码到支持 Mermaid 的编辑器查看可视化图表")
    print("   推荐工具: https://mermaid.live/, VS Code (Mermaid 插件), Typora")
    print(f"{separator}\n")


def visualize_workflow(
    workflow: CompiledStateGraph,
    output_path: Optional[str] = None,
    format: Literal["mermaid", "ascii", "json"] = "mermaid",
    title: str = "Workflow Graph",
) -> str:
    """可视化工作流（高级函数）。

    提供多种格式的可视化选项，并可选择保存到文件或返回字符串。

    Args:
        workflow: 编译后的工作流
        output_path: 输出路径（可选）
        format: 输出格式
            - "mermaid": Mermaid 图表代码（默认）
            - "ascii": 简化的 ASCII 艺术表示
            - "json": 结构化的 JSON 格式
        title: 图表标题

    Returns:
        格式化后的图表字符串

    Raises:
        ValueError: 如果 format 参数无效

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)

        >>> # 获取 Mermaid 格式
        >>> mermaid = visualize_workflow(workflow, format="mermaid")

        >>> # 获取 ASCII 格式
        >>> ascii_art = visualize_workflow(workflow, format="ascii")

        >>> # 保存到文件
        >>> visualize_workflow(workflow, "output.mmd", format="mermaid")
    """
    if workflow is None:
        raise ValueError("Workflow cannot be None")

    if format == "mermaid":
        result = get_graph_mermaid(workflow, title)
    elif format == "ascii":
        result = _generate_ascii_graph(workflow)
    elif format == "json":
        result = _generate_json_graph(workflow, title)
    else:
        raise ValueError(
            f"Invalid format '{format}'. Supported formats: 'mermaid', 'ascii', 'json'"
        )

    # 如果指定了输出路径，保存到文件
    if output_path:
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(result)

    return result


def generate_html_viewer(
    workflow: CompiledStateGraph, output_path: str, title: str = "Workflow Graph"
) -> None:
    """生成包含 Mermaid.js 的 HTML 可视化文件。

    创建一个独立的 HTML 文件，可在浏览器中直接打开查看工作流图。
    该文件包含 Mermaid.js 库，无需额外依赖。

    Args:
        workflow: 编译后的工作流
        output_path: 输出 HTML 文件的路径
        title: 图表标题

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)
        >>> generate_html_viewer(workflow, "workflow.html", "查询工作流")
        >>> # 在浏览器中打开 workflow.html 查看可视化
    """
    mermaid_code = get_graph_mermaid(workflow, title)

    html_template = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Workflow Visualization</title>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{
            startOnLoad: true,
            theme: 'default',
            securityLevel: 'loose',
            flowchart: {{
                curve: 'linear',
                padding: 20
            }}
        }});
    </script>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            margin: 0;
            padding: 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            padding: 40px;
        }}
        h1 {{
            color: #333;
            text-align: center;
            margin-bottom: 10px;
            font-size: 28px;
        }}
        .subtitle {{
            text-align: center;
            color: #666;
            margin-bottom: 30px;
            font-size: 14px;
        }}
        .mermaid {{
            padding: 20px;
            background: #f8f9fa;
            border-radius: 8px;
        }}
        .footer {{
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
            padding-top: 20px;
            border-top: 1px solid #e0e0e0;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p class="subtitle">LangGraph Workflow Visualization - Generated by Medical-Graph-RAG</p>
        <div class="mermaid">
{mermaid_code}
        </div>
        <div class="footer">
            <p>提示: 可以直接在浏览器中查看此图表，或复制 Mermaid 代码到其他编辑器</p>
        </div>
    </div>
</body>
</html>"""

    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html_template)


def generate_dot_format(
    workflow: CompiledStateGraph, output_path: str, title: str = "Workflow Graph"
) -> None:
    """导出 GraphViz DOT 格式的工作流图。

    生成 GraphViz DOT 格式的文件，可使用 GraphViz 工具集
    渲染为高质量图片（PNG, SVG, PDF 等）。

    Args:
        workflow: 编译后的工作流
        output_path: 输出 DOT 文件的路径
        title: 图表标题

    Example:
        >>> from src.agents.workflows.query import create_query_workflow
        >>> workflow = create_query_workflow(rag_adapter)
        >>> generate_dot_format(workflow, "workflow.dot")
        >>> # 使用 GraphViz 渲染: dot -Tpng workflow.dot -o workflow.png
    """
    mermaid_code = get_graph_mermaid(workflow, title)

    # 转换 Mermaid 到 DOT 格式（简化版本）
    dot_content = _mermaid_to_dot(mermaid_code, title)

    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(dot_content)


# ==================== 辅助函数 ====================


def _generate_ascii_graph(workflow: CompiledStateGraph) -> str:
    """生成简化的 ASCII 艺术表示。

    Args:
        workflow: 编译后的工作流

    Returns:
        ASCII 艺术字符串
    """
    try:
        graph = workflow.get_graph()

        # 获取所有节点
        nodes = list(graph.nodes.keys())

        if not nodes:
            return "Empty workflow"

        # 构建 ASCII 表示
        lines = []
        lines.append("┌─ WORKFLOW STRUCTURE ─────────────────────────────┐")
        lines.append("│")

        # 显示节点
        for i, node in enumerate(nodes):
            connector = "├─" if i < len(nodes) - 1 else "└─"
            lines.append(f"│ {connector} [{node}]")

            # 尝试获取节点的出边
            try:
                edges = list(graph.edges(node))
                for j, (_, target) in enumerate(edges):
                    edge_connector = "│  ├─" if j < len(edges) - 1 else "│  └─"
                    lines.append(f"{edge_connector}→ {target}")
            except Exception:  # noqa: F841 - 静默处理异常，用于容错展示
                pass

        lines.append("│")
        lines.append("└──────────────────────────────────────────────────┘")

        return "\n".join(lines)

    except Exception as e:
        return f"Error generating ASCII graph: {str(e)}"


def _generate_json_graph(workflow: CompiledStateGraph, title: str) -> str:
    """生成结构化的 JSON 格式。

    Args:
        workflow: 编译后的工作流
        title: 图表标题

    Returns:
        JSON 格式字符串
    """
    try:
        graph = workflow.get_graph()

        # 提取节点信息
        nodes_data = []
        for node_id, node in graph.nodes.items():
            nodes_data.append({"id": node_id, "type": str(type(node).__name__)})

        # 提取边信息
        edges_data = []
        try:
            for source, target in graph.edges:
                edges_data.append({"from": str(source), "to": str(target)})
        except Exception:  # noqa: F841 - 静默处理异常，用于容错展示
            pass

        # 构建 JSON 结构
        workflow_json = {
            "title": title,
            "type": "LangGraph Workflow",
            "nodes": nodes_data,
            "edges": edges_data,
            "node_count": len(nodes_data),
            "edge_count": len(edges_data),
        }

        return json.dumps(workflow_json, indent=2, ensure_ascii=False)

    except Exception as e:
        error_json = {"error": f"Error generating JSON graph: {str(e)}", "title": title}
        return json.dumps(error_json, indent=2, ensure_ascii=False)


def _mermaid_to_dot(mermaid_code: str, title: str) -> str:
    """将 Mermaid 代码转换为 GraphViz DOT 格式。

    这是一个简化的转换函数，提供基本的 DOT 格式支持。

    Args:
        mermaid_code: Mermaid 格式的代码
        title: 图表标题

    Returns:
        DOT 格式代码
    """
    # 简化的转换逻辑
    lines = mermaid_code.split("\n")
    dot_lines = []

    dot_lines.append(f"// {title}")
    dot_lines.append("// Converted from Mermaid format")
    dot_lines.append("digraph workflow {")
    dot_lines.append("    rankdir=TD;")
    dot_lines.append("    node [shape=box, style=rounded];")
    dot_lines.append("")

    for line in lines:
        line = line.strip()
        if line.startswith("%%") or not line or line.startswith("graph TD;"):
            continue
        if line.startswith("classDef") or line.startswith("%%{init"):
            continue

        # 转换节点和边
        line = line.replace("-->", "->")
        line = line.replace("-.->", "-> [style=dashed]")
        line = line.replace("([", ' [shape=ellipse, label="')
        line = line.replace("])", '"]')

        if line and not line.startswith("%%"):
            dot_lines.append(f"    {line}")

    dot_lines.append("}")
    return "\n".join(dot_lines)


def compare_workflows(
    *workflows: CompiledStateGraph,
    titles: Optional[list[str]] = None,
    output_path: Optional[str] = None,
) -> str:
    """比较多个工作流的结构。

    生成并列显示多个工作流的 Mermaid 图表，便于比较差异。

    Args:
        *workflows: 多个编译后的工作流
        titles: 工作流标题列表（可选）
        output_path: 输出文件路径（可选）

    Returns:
        组合的 Mermaid 代码

    Example:
        >>> query_workflow = create_query_workflow(rag_adapter)
        >>> build_workflow = create_build_workflow(rag_adapter)
        >>> compare = compare_workflows(
        ...     query_workflow, build_workflow,
        ...     titles=["查询工作流", "构建工作流"],
        ...     output_path="comparison.mmd"
        ... )
    """
    if not workflows:
        return "%% No workflows provided"

    if titles is None:
        titles = [f"Workflow {i + 1}" for i in range(len(workflows))]

    if len(titles) != len(workflows):
        raise ValueError("Number of titles must match number of workflows")

    # 为每个工作流生成子图
    subgraphs = []
    for i, (workflow, title) in enumerate(zip(workflows, titles)):
        mermaid = get_graph_mermaid(workflow, title)
        subgraph = f"    subgraph {title.replace(' ', '_')}\n{mermaid}\n    end"
        subgraphs.append(subgraph)

    # 组合成一个 Mermaid 图表
    combined = "%% Workflow Comparison\n"
    combined += "%% Generated by Medical-Graph-RAG Visualization Module\n\n"
    combined += "graph TB\n"
    combined += "\n".join(subgraphs)

    if output_path:
        save_graph_mermaid(workflows[0], output_path, "Workflow Comparison")

    return combined
